name: ml_kit_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_ml_vision: ^0.9.3
  firebase_storage: ^3.0.6
  cloud_firestore: ^0.12.9+6
  image_picker: ^0.6.1+10
  google_maps_flutter: ^0.5.21+8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
